### ISSUE TITLE
No PaymentPaid event 

### ISSUE THREAD

**Issue by Nanoapplics** [Azuriom/Plugin-DedipassPayment#2]
The plugin does not contain an event "PaymentPaid" currently, it must be added either.

**Comment by MrMicky-FR** [comment]
The `PaymentPaid` is called, as the plugin calls the `Payment::deliver()` method:
https://github.com/Azuriom/Plugin-DedipassPayment/blob/6c15e50ae6d083a7d552683b7c6417188774abf3/src/DediPassMethod.php#L107

Which calls the `PaymentPaid` event:
https://github.com/Azuriom/Plugin-Shop/blob/4081d93430b6652a88b5d777ac048393601e2c11/src/Models/Payment.php#L104
